services:
  postgres:
    build:
      context: .
      target: postgres_image
    container_name: postgres
    env_file:
      - .env.user
    ports:
      - "5435:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - postgres_data:/var/lib/postgresql/data


  data_generator:
    profiles:
      - tools
    build:
      context: .
      target: data_generator
    container_name: data-generator
    env_file:
      - .env.user
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./app/queries/charts:/app/app/queries/charts

  etl:
    profiles:
      - tools
    build:
      context: .
      target: etl
    env_file:
      - .env.user
    container_name: etl-container
    depends_on:
      data_generator:
        condition: service_completed_successfully

  validate_pipelines:
    profiles:
      - tools
    build:
      context: .
      target: validate_pipelines
    env_file:
      - .env.user
    container_name: pipeline-validation
    depends_on:
      etl:
        condition: service_completed_successfully

  create_charts:
    profiles:
      - tools
    build:
      context: .
      target: create_charts
    container_name: create_charts
    env_file:
      - .env.user
    depends_on:
      etl:
        condition: service_completed_successfully
    volumes:
      - ./app/queries/charts:/app/app/queries/charts

volumes:
  postgres_data:
  charts_data:
