services:
  postgres:
    build: .
    container_name: postgres
    env_file:
      -  .env
    ports:
      -  "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  python_app:
    build:
        context: ./app
    container_name: python-app
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres_data:
